from __future__ import annotations

PURPOSE_COLLECT = "collect"
PURPOSE_INSTANT_REPORT = "instant_report"
PURPOSE_INTERNAL_IMPROVEMENT = "internal_improvement"
PURPOSE_PARTNER_SHARING = "partner_sharing"
PURPOSE_FOLLOW_UP_CONTACT = "follow_up_contact"

PURPOSE_CODES = (
    PURPOSE_COLLECT,
    PURPOSE_INSTANT_REPORT,
    PURPOSE_INTERNAL_IMPROVEMENT,
    PURPOSE_PARTNER_SHARING,
    PURPOSE_FOLLOW_UP_CONTACT,
)

PURPOSE_LABELS = {
    PURPOSE_COLLECT: "采集体验数据",
    PURPOSE_INSTANT_REPORT: "生成即时结论",
    PURPOSE_INTERNAL_IMPROVEMENT: "内部产品改进",
    PURPOSE_PARTNER_SHARING: "向指定合作方共享",
    PURPOSE_FOLLOW_UP_CONTACT: "后续联系",
}

# 未获采集授权时不可能有意义地授权的下游用途
DOWNSTREAM_PURPOSES = (
    PURPOSE_INSTANT_REPORT,
    PURPOSE_INTERNAL_IMPROVEMENT,
    PURPOSE_PARTNER_SHARING,
    PURPOSE_FOLLOW_UP_CONTACT,
)
